### ISSUE TITLE
Script suddenly stopped working, different error codes

### ISSUE THREAD

**Issue by axellencyDE** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#85] opened 2023-11-17 08:24 UTC
I used the script for a while and it worked flawlessly. I didn't change anything but now it throws errors. Most times it is this one: 

Error: Request failed for https://i.instagram.com/ returned code **401**. Truncated server response: {"message":"請幾分鐘後再試一次。","require_login":true,"status":"fail"} (use muteHttpExceptions option to examine full response) (error code: 0xf1)

And often it is this one:

Error: Request failed for https://i.instagram.com/ returned code **500**. Truncated server response: Oops, an error occurred. (use muteHttpExceptions option to examine full response) (error code: 0xf1)

Does anybody have an idea how to resolve this?

Thanks,
Axel

**Comment by chriskyfung** [comment] 2023-11-17 08:52
Yes, Instagram forced you out.
You shall log in the Instagram website regularly using Chrome on your PC. Otherwise，the cookies and the session will become invalid very soon.

**Comment by chriskyfung** [comment] 2023-11-18 07:54
You got such API response because of a security measure that Instagram uses to protect users’ accounts from unauthorized access or hacking. It is part of a new feature called [Security Checkup, launched in July 2021](https://about.instagram.com/blog/announcements/keeping-instagram-safe-and-secure).

When you open the Instagram website in a browser, you will be redirected to check and update their login and profile information. It may also ask users to enter a code or upload a photo to verify their identity.

![Help us confirm it's you](https://github.com/chriskyfung/AutoFetcher-IG-Stories-to-GDrive/assets/8746768/f76ce628-4e1f-419e-bd37-ea2d9c9f4b10)

> **Help us confirm it's you**
>
> We've noticed unusual activity from your account and have temporarily restricted certain actions.
>
> Follow the next steps to help us remove the restrictions on your account.

**Duplicate of #45**

**Closed by chriskyfung** 2023-11-18 07:54 UTC
Labels: documentation, duplicate
